services:
  DesnaRobot:
    image: nginx:alpine
    container_name: DesnaRobot
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-9090}:80"
    environment:
      - TRUSTED_PROXY_IP=${TRUSTED_PROXY_IP}
      - WEBHOOK_SITE=${WEBHOOK_SITE}
      - WEBHOOK_APP=${WEBHOOK_APP}
      - WEBHOOK_SCHEDULE_GET=${WEBHOOK_SCHEDULE_GET}
      - WEBHOOK_SCHEDULE_SET=${WEBHOOK_SCHEDULE_SET}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./docker/50-generate-static-config.sh:/docker-entrypoint.d/50-generate-static-config.sh:ro
      - ./html/config.js.template:/docker-templates/config.js.template:ro
      - ./html/admin/config.js.template:/docker-templates/admin.config.js.template:ro
